# -*- coding: utf-8 -*-
"""Content for the 32 Anne-unit Writer's Workshop cards (G4 ELA, Weeks 7-14).
One dict per lesson day. Rendered by build.py."""

STEPS = ["Voice", "Character", "Conflict", "Draft Open", "Rising Action", "Revise", "Edit", "Publish"]
WEEK_STEP = {7: 0, 8: 1, 9: 2, 10: 3, 11: 4, 12: 5, 13: 6, 14: 7}
WEEK_LABEL = {7: "VOICE", 8: "CHARACTER", 9: "CONFLICT", 10: "DRAFT THE OPENING",
              11: "RISING ACTION", 12: "REVISE", 13: "EDIT", 14: "PUBLISH"}

FILES = {
    (7,1):"lesson-7-1-anne-ch1.html",(7,2):"lesson-7-2-anne-ch2.html",(7,3):"lesson-7-3-anne-ch3-4.html",(7,4):"lesson-7-4-anne-ch5.html",
    (8,1):"lesson-8-1-anne-ch6.html",(8,2):"lesson-8-2-anne-ch7-8.html",(8,3):"lesson-8-3-anne-ch9.html",(8,4):"lesson-8-4-anne-ch10.html",
    (9,1):"lesson-9-1-anne-ch11.html",(9,2):"lesson-9-2-anne-ch12-13.html",(9,3):"lesson-9-3-anne-ch14.html",(9,4):"lesson-9-4-anne-ch15.html",
    (10,1):"lesson-10-1-anne-ch16.html",(10,2):"lesson-10-2-anne-ch17-18.html",(10,3):"lesson-10-3-anne-ch19.html",(10,4):"lesson-10-4-anne-ch20.html",
    (11,1):"lesson-11-1-anne-ch21.html",(11,2):"lesson-11-2-anne-ch22-23.html",(11,3):"lesson-11-3-anne-ch24.html",(11,4):"lesson-11-4-anne-ch25.html",
    (12,1):"lesson-12-1-anne-ch26.html",(12,2):"lesson-12-2-anne-ch27-28.html",(12,3):"lesson-12-3-anne-ch29.html",(12,4):"lesson-12-4-anne-ch30.html",
    (13,1):"lesson-13-1-anne-ch31.html",(13,2):"lesson-13-2-anne-ch32.html",(13,3):"lesson-13-3-anne-ch33.html",(13,4):"lesson-13-4-anne-ch34.html",
    (14,1):"lesson-14-1-anne-ch35.html",(14,2):"lesson-14-2-anne-ch36.html",(14,3):"lesson-14-3-anne-ch37.html",(14,4):"lesson-14-4-anne-ch38.html",
}

# Sam's story, as it stands at each point. Used in Watch How panels.
SAM_S1 = "“You’re going to be late!” Mom shouted up the stairs. Mateo froze with one cleat on. Today was tryouts. He had wanted to make the team since he was seven. He had also wanted, every single day since, to skip it."
SAM_S2 = "At the field, twenty boys were already kicking balls around like it was nothing. Mateo stopped at the edge of the grass. Diego jogged over. “You came,” he said. Mateo nodded. Inside, he thought: Don’t throw up. Don’t throw up. Don’t throw up."
SAM_S3_DRAFT = "First came sprints. Coach yelled “FASTER!” like he meant it. Mateo’s dad came to watch. Halfway down the field Mateo’s left cleat caught his right one and he went down in front of everyone. He lay there and thought about the gate. It was only twenty steps away. Somebody laughed."
SAM_S3_FINAL = "First came sprints. Coach yelled “FASTER!” like he meant it. Sweat ran down Mateo’s neck. He could hear his heart in his ears. Halfway down the field his left cleat caught his right one and he went down in front of everyone. Somebody laughed. Mateo lay there with grass in his mouth and thought about the gate. It was only twenty steps away."
SAM_S4_DRAFT = "Then a hand came down in front of his face. Diego. “Are you okay?” Diego said. Mateo got up. His knee was bleeding a little. He walked back to the line, and when Coach called penalty kicks, he was the first one there. He kicked the ball. It went wide. He didn’t care."
SAM_S4_FINAL = "Then a hand came down in front of his face. Diego. He didn’t say anything. He just pulled. Mateo got up. His knee was bleeding a little. He walked back to the line, and when Coach called penalty kicks, he was the first one there. He slammed the ball. It went wide. He didn’t care."
SAM_S5_ROUGH = "Mateo made the team. He was happy. The end."
SAM_S5_STRONG = "Mateo walked off the field with the team list in his pocket. The same field that looked huge an hour ago now felt small. “Next year,” he told Diego, “I won’t be scared at all.” Diego laughed. “Yes you will.” Mateo grinned. He probably would. He’d come anyway."

CARDS = {}

def card(w, d, **k):
    k.update(week=w, day=d)
    CARDS[(w, d)] = k

# ---------------------------------------------------------------- WEEK 7 · VOICE
card(7,1, sub="Day 1: Find your kid",
 focus="This is the start of an eight-week project. You are going to write one realistic-fiction story, about one page long, one piece at a time. Realistic fiction means a kid who could be real, in a place that could be real, facing something kids really face. Today you pick the kid and the thing.",
 anne="Montgomery spends all of Chapter 1 on a nosy neighbor and a road. But the whole book is about the kid nobody expected. Your story is about a kid too. Start there.",
 watch=dict(intro="Meet Sam. Sam is a 4th-grade writer, and today Sam is picking what his story will be about. He lists three things a kid his age might really face.",
   page=["1. Starting at a new school in the middle of the year.","2. Losing a dog and looking for it.","3. Being scared to try out for the soccer team."],
   notice="Sam picks #3 — not because it’s the most exciting, but because he knows exactly how it feels. Pick the one you know from the inside."),
 tool=dict(title="Idea list", intro="Three real things a kid your age might face. Then circle one.",
   filled=["Sam’s: new school · lost dog · <b>scared of tryouts</b> ← this one",
           "Good kinds of ideas: a first time, a mistake, a friend problem, wanting something badly, a move, a dare, a big day."],
   yourturn="Idea 1: ____ · Idea 2: ____ · Idea 3: ____ → circle one."),
 frames=["My story is about a [kid] who ___.","The thing my kid has to face is ___.","I know how that feels because ___.","By the end, my kid learns ___."],
 ms="Nothing to draft yet — this week and the next two are planning. Scene 1 goes in here in Week 10. (This box saves on this computer, in this browser. If you switch computers, keep a copy somewhere else too.)",
 prompt="Pick a growing-up thing your kid will face (imagination, friendship, a mistake, wanting something, being new, being scared). Then write the one sentence that starts everything: “My story is about a [kid] who [realistic situation] and learns about [that thing].”",
 ph="My story is about a... who... and learns about...")

card(7,2, sub="Day 2: Name, want, fear",
 focus="Your kid needs three things before they can talk: a name, one thing they want, and one thing they’re afraid of. Make all three specific. “Wants to be happy” is not specific. “Wants to make the team” is.",
 anne="In Chapter 2, Anne wants to stay at Green Gables so badly she can’t stop talking about it. We know what she wants before we know her last name.",
 watch=dict(intro="Sam makes a character card for his kid.",
   page=["<b>Name:</b> Mateo Hernandez, 10","<b>Wants:</b> to make the soccer team","<b>Afraid of:</b> looking stupid in front of Diego, his best friend","<b>One odd detail:</b> ties and unties his cleats when he’s nervous"],
   notice="Every line is something you could see or point to. “Afraid of looking stupid in front of Diego” is better than “afraid of failing” because it has a person in it."),
 tool=dict(title="Character card", intro="Five lines. Keep each one short and real.",
   filled=["Name and age","One thing they want","One thing they’re afraid of","One odd detail (a habit, a thing they carry, a way they talk)","Where they are most days (home, school, a field, a bus)"],
   yourturn="Name: ____ · Wants: ____ · Afraid of: ____ · Odd detail: ____ · Where: ____"),
 frames=["My kid’s name is ___, and they are ___ years old.","More than anything, they want ___.","The thing they’re most afraid of is ___.","One odd thing about them: ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Build your kid. In 2–3 sentences: their name, ONE specific thing they want, ONE specific thing they’re afraid of. Specific means a real detail, not a feeling word.",
 ph="My kid's name is ___. They want ___. They're afraid of ___.")

card(7,3, sub="Day 3: Voice is word choice",
 focus="VOICE is the way your kid sounds — and it comes from the words you pick. Not “nice,” not “bad,” not “went.” Specific verbs and specific nouns make a kid sound like a real person instead of a list of facts.",
 anne="In Chapter 3, Anne asks to be called Cordelia, then settles for Anne — but only if it’s spelled with an e. Nobody else on Prince Edward Island cares about the e. That’s voice.",
 watch=dict(intro="Sam writes one moment of Mateo the plain way, then goes back and swaps in specific words.",
   before="Mateo was nervous. He looked at the field. He felt bad.",
   after="Mateo’s hands felt cold. He stared at the field, kicking dirt with his toe. “Don’t throw up,” he whispered to himself.",
   notice="hands felt cold, stared, kicking dirt, don’t throw up. The second version never says “nervous,” and you know he is. Specific words show. General words tell."),
 tool=dict(title="Word-choice planner", intro="Boring word on the left, specific word on the right.",
   table=[["Type","Boring","Specific"],["Adjective","nice field","green, freshly cut field"],["Verb","said quietly","whispered"],["Verb","went fast","sprinted, raced, dashed"],["Noun","a boy","Mateo"]],
   yourturn="Three boring words you might use for your kid → three upgrades."),
 frames=["[Kid]’s [body part] felt ___.","[Kid] [specific verb]-ed the ___.","“___,” [kid] whispered / muttered / yelled.","The ___ was [specific adjective]."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Write 2–3 sentences in YOUR kid’s voice. Don’t describe them — let them say or do something. Pick the words they would really use.",
 ph="[Kid] said, \"...\"")

card(7,4, sub="Day 4: Voice under pressure",
 focus="You find out who a kid really is when something goes wrong. Today your kid gets bad news. Show how they sound and what they do — three ways: what they say, what they do, what their body does. Don’t write “she was sad.”",
 anne="In Chapter 5, Anne is being driven away from the one place she wants to stay, and she still can’t help noticing the shore. That reaction belongs to Anne and nobody else.",
 watch=dict(intro="Sam gives Mateo bad news: Diego signed up for tryouts too.",
   before="Mateo was upset when he found out Diego was trying out.",
   after="“Cool,” Mateo said. He tied his cleat. He untied it. He tied it again, tighter, until his foot hurt.",
   notice="What he says: one word, and it’s a lie. What he does: the cleat thing from his character card. What his body does: he pulls the lace until it hurts. Three moves, no feeling words."),
 tool=dict(title="Reaction ladder", intro="Three rungs. Climb all three.",
   filled=["<b>Says:</b> “Cool.” (one word, not true)","<b>Does:</b> ties and unties the cleat","<b>Body:</b> pulls the lace until his foot hurts"],
   yourturn="Says: ____ · Does: ____ · Body: ____"),
 frames=["“___,” [kid] said, which wasn’t true.","[Kid] [did the odd habit from the character card].","[Kid]’s [body part] ___.","[Kid] didn’t say anything. [Kid] just ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Show your kid REACTING to disappointment. Use the ladder: what they say, what they do, what their body does. No feeling words.",
 ph="\"___,\" [kid] said. Then they ___. Their ___ ...")

# ---------------------------------------------------------------- WEEK 8 · CHARACTER
card(8,1, sub="Day 1: Show, don’t tell",
 focus="Real characters have specific feelings, and the writer never names them. Instead you use three kinds of detail: something the body does, something the senses catch, and something the kid says. This is the most useful trick in the whole project.",
 anne="In Chapter 6, Marilla decides to keep Anne. She never says so in that scene. You know it from what she does with Mrs. Blewett.",
 watch=dict(intro="Sam takes one feeling word and replaces it with three kinds of detail.",
   before="Mateo was scared.",
   after="Mateo’s knees wobbled like wet paper. The whistle screamed and he flinched. “You can do this,” he whispered. “You can do this.”",
   notice="A body detail (knees like wet paper), a sensory detail (the whistle screamed), and dialogue the kid says to himself. Three kinds of detail doing one job."),
 tool=dict(title="Detail chart", intro="Four rows. Use at least two whenever you’re about to write a feeling word.",
   table=[["Kind of detail","Sam’s, for Mateo"],["Body (show feelings)","knees wobbled like wet paper"],["Sensory (see / hear / smell / touch)","the whistle screamed"],["Dialogue","“You can do this,” he whispered"],["Appearance","his jersey hung loose on his thin shoulders"]],
   yourturn="Body: ____ · Sensory: ____ · Dialogue: ____ · Appearance: ____"),
 frames=["[Kid]’s [body part] felt like ___.","The ___ [sound verb]-ed and [kid] ___.","“___,” [kid] whispered / cried / laughed.","[Kid]’s [thing] hung / sat / leaned ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Write ONE sentence about your kid that uses a feeling word (scared, happy, angry, embarrassed). Then rewrite it with no feeling word: a body detail, a sensory detail, and one line of dialogue.",
 ph="Feeling word version: ___ / Rewrite: ___")

card(8,2, sub="Day 2: Inner life",
 focus="What does your kid think when no one is there? Readers feel close to a character when they get to hear the private thoughts — the wishes, the worries, the things they’d never say out loud.",
 anne="In Chapter 7, Anne says her first prayer, and it tells you more about her than a page of description could. It’s what she thinks when she believes only God is listening.",
 watch=dict(intro="Sam writes Mateo the night before tryouts, alone in bed.",
   page=["Mateo lay in the dark and did the math. Twenty kids trying out. Fifteen spots. Five kids going home. Outside he’d told Diego, “It’s no big deal.” Inside he was already one of the five."],
   notice="Outside / inside. What Mateo says to Diego and what he thinks in the dark are two different things, and the gap between them is the character."),
 tool=dict(title="Outside / inside", intro="Two lines. The gap between them is your kid.",
   filled=["<b>Outside</b> (what they say or show): “It’s no big deal.”","<b>Inside</b> (what they really think): already counting himself out"],
   yourturn="Outside, my kid ____. Inside, my kid ____."),
 frames=["Outside, [kid] ___. Inside, ___.","[Kid] lay in the dark and thought about ___.","What [kid] wished, more than anything, was ___.","Nobody knew that [kid] ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Write 2–3 sentences of your kid alone, thinking. What do they wish for? What do they worry about? Use their own words — the ones they’d use in their head.",
 ph="When [kid] is alone, they think about ___...")

card(8,3, sub="Day 3: Where they come from, and who else is there",
 focus="Two things today. First, a little history: where your kid is from and what they’ve already been through. Second, the other person in your story — a friend, a grown-up, or a rival. A story needs at least two people.",
 anne="In Chapter 9, one rude remark about red hair and we get Anne’s whole history in her reaction. And Mrs. Lynde is the other person — the story needs her.",
 watch=dict(intro="Sam writes Mateo’s history in two sentences, then names the other person.",
   page=["<b>History:</b> Mateo has moved twice in three years. His dad played soccer in Mexico and never talks about it, which is how Mateo knows it mattered.","<b>The other person:</b> Diego — best friend, better at soccer, and the one Mateo can’t stand to look bad in front of."],
   notice="Two sentences of history, and one of them is about the dad. The other person isn’t a villain. He’s a friend, which makes it harder."),
 tool=dict(title="Backstory + the other person", intro="Pick ONE other person and say what they are to your kid.",
   filled=["<b>A friend</b> — someone who’s on their side, which can make things harder","<b>A grown-up</b> — a parent, coach, teacher, neighbor","<b>A rival</b> — someone they’re measuring themselves against"],
   yourturn="History (2 sentences): ____ · The other person: ____, who is my kid’s ____."),
 frames=["[Kid] has ___ since ___.","[Kid]’s [family member] ___, and never talks about it.","The other person in my story is ___.","[Other person] is [kid]’s ___, which means ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Write 2–3 sentences of your kid’s history (where they’re from, what they’ve been through). Then one sentence naming the other person in your story and what they are to your kid.",
 ph="[Kid] is from ___. They have ___. / The other person is ___, my kid's ___.")

card(8,4, sub="Day 4: The change",
 focus="A story is a kid who is different at the end than at the start. Today you decide what that change is. You don’t have to know how it happens yet. You just need the two ends: how they think at the start, how they think at the end.",
 anne="In Chapter 10, Anne apologizes to Mrs. Lynde. It’s the first time she does the hard thing on purpose. That’s the first sign she’s changing.",
 watch=dict(intro="Sam fills in two columns for Mateo.",
   table=[["At the start","By the end"],["Thinks being scared means he doesn’t belong there","Knows being scared and going anyway is the whole point"],["Wants to make the team","Still wants it — but finishes tryouts before he knows if he did"]],
   notice="The change isn’t “he makes the team.” It’s what he thinks scared means. The team list is just how the story ends. The change is what the story is about."),
 tool=dict(title="Start / end", intro="Two columns. What your kid believes at the start, what they believe at the end.",
   filled=["Start: what they think about themselves, or about the problem","End: what they think now — after the story"],
   yourturn="At the start, my kid thinks ____. By the end, my kid knows ____."),
 frames=["At the start, [kid] thinks ___.","By the end, [kid] knows ___.","[Kid] still wants ___, but now ___.","The story changes [kid] from ___ to ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Write 2–3 sentences: how your kid thinks or feels at the START of your story, and how they think or feel at the END. That change is your story’s shape.",
 ph="At the start, my kid... By the end, my kid...")

# ---------------------------------------------------------------- WEEK 9 · CONFLICT
card(9,1, sub="Day 1: A want and a wall",
 focus="Conflict is simple: your kid wants something, and something is in the way. Today you name both, as specifically as you can. The want is from your character card. The wall is new.",
 anne="Chapter 11 opens with three plain dresses and no puffed sleeves. Anne wants puffed sleeves. Marilla is the wall. Small want, real wall.",
 watch=dict(intro="Sam names his want and his wall.",
   page=["<b>Want:</b> Mateo wants to make the team.","<b>Wall:</b> He is so scared of looking bad in front of Diego that he might not even try."],
   notice="The wall isn’t “the other kids are better.” The wall is inside Mateo. That’s fine — a wall can be a person, a rule, or a fear. Sam’s is a fear."),
 tool=dict(title="Want + wall", intro="One line each. Be specific.",
   filled=["<b>Want:</b> a thing, a place, a friend, a moment — something you could point at","<b>Wall:</b> the one thing or person that makes it hard"],
   yourturn="My kid wants ____. What’s in the way is ____."),
 frames=["[Kid] wanted ___ more than anything.","But ___ kept getting in the way.","The problem wasn’t ___. The problem was ___.","Every time [kid] got close, ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Conflict starts with a want. Write 2–3 sentences: name ONE specific thing your kid wants. Then name ONE thing or person that makes it hard to get.",
 ph="My kid wants ___. What gets in the way is ___.")

card(9,2, sub="Day 2: Three kinds of wall",
 focus="Walls come in three kinds: a person (someone who blocks them), a rule (something they aren’t allowed to do), or a fear (something inside them). Most good stories have one main wall and a second, smaller one.",
 anne="In Chapter 12, Anne wants Diana for a bosom friend, and the wall is her own fear that Diana won’t like her. A fear counts as a wall.",
 watch=dict(intro="Sam sorts his walls.",
   page=["<b>Main wall — a fear:</b> Mateo is scared of looking stupid in front of Diego.","<b>Smaller wall — a rule:</b> Tryouts are one day only. Coach doesn’t do second chances."],
   notice="The rule makes the fear worse. If Mateo walks off, that’s it for the year. Two walls, and one presses on the other."),
 tool=dict(title="Wall sorter", intro="Pick your main wall. Then find a smaller one of a different kind.",
   table=[["Kind","What it looks like","Sam’s"],["Person","someone who blocks, teases, or competes","(Diego is a friend, not a wall)"],["Rule","something they can’t do, or must do","one day, no second chances"],["Fear","something inside them","looking stupid in front of Diego"]],
   yourturn="Main wall (person / rule / fear): ____. Smaller wall: ____."),
 frames=["[Kid]’s biggest problem is a [person / rule / fear]: ___.","On top of that, ___.","The rule was simple: ___.","Nobody was stopping [kid] except ___."],
 ms="Still planning. Nothing to draft yet.",
 prompt="Name the kind of wall your kid faces — a person, a rule, or a fear — and say exactly what it is. Then add one smaller wall of a different kind. 2–3 sentences.",
 ph="My kid's main wall is a [person / rule / fear]: ___. A smaller wall is ___.")

card(9,3, sub="Day 3: Map the story",
 focus="Today you map the whole story: a beginning, a middle where three things make the problem worse, and an end. You aren’t writing scenes yet. You’re drawing the shape so that when you write, you know where you’re going.",
 anne="Chapter 14 is a map. One small lie about the brooch, three things go wrong because of it, and a confession at the end. Beginning, middle, end, in one chapter.",
 watch=dict(intro="Sam fills in the Parts of a Narrative map.",
   table=[["Part","Its job","Sam’s"],["\U0001F7E2 Beginning","Kid + setting + want","The morning of tryouts. Mateo wants to make the team and can’t make himself put his cleat on."],["\U0001F7E1 Middle","Three things that make it worse","1. At the field, twenty boys look like they belong, and Mateo almost turns around. 2. He trips in sprints in front of everyone and thinks about the gate. 3. Coach calls penalty kicks and Mateo’s knee is bleeding."],["\U0001F534 End","How it resolves and what changes","Mateo finishes — before he even sees the list."]],
   notice="The middle has THREE things, and each one is worse than the last. That’s what keeps a reader reading. One problem is a moment. Three is a story. Tomorrow each part of this map becomes one scene, so keep it."),
 tool=dict(title="Parts of a Narrative", intro="Beginning, middle, end. The middle gets three things.",
   filled=["\U0001F7E2 <b>Beginning:</b> hook the reader, introduce the kid and what they want","\U0001F7E1 <b>Middle:</b> three things that get in the way, each worse than the last","\U0001F534 <b>End:</b> how it resolves, and what changed in the kid"],
   yourturn="Beginning: ____ · Middle 1: ____ · Middle 2: ____ · Middle 3: ____ · End: ____"),
 frames=["[Kid] wanted ___, but ___.","First, ___. Then, worse, ___. Then, worst of all, ___.","Just when [kid] thought ___, ___ happened.","In the end, [kid] ___."],
 ms="Still planning. Tomorrow you turn today’s map into five scenes and paste them at the top of this box.",
 prompt="Fill in YOUR map. Beginning (kid + setting + want). Middle (THREE things that get in the way, worst last). End (how it resolves, what changes).",
 ph="Beginning: ___ / Middle 1: ___ / Middle 2: ___ / Middle 3: ___ / End: ___")

card(9,4, sub="Day 4: Five scenes",
 focus="A story is written in scenes. Your story will have five: an opening, the first wall, the worst moment, what your kid does about it, and an ending. Today you name all five in one line each. Next week you start writing them.",
 anne="Chapter 15 is one scene — the slate, Gilbert, the classroom — and Montgomery gives it a whole chapter. One scene, told all the way through, is worth more than five half-told.",
 watch=dict(intro="Sam turns yesterday’s map into five scenes. Each part of the map becomes one scene: the Beginning is Scene 1, the three middle things are Scenes 2, 3 and 4, and the End is Scene 5.",
   page=["<b>Scene 1 — Opening</b> (map: Beginning): Morning of tryouts. Mom yells. Mateo can’t get his cleat on.","<b>Scene 2 — First wall</b> (map: Middle 1): At the field. Twenty boys. Diego says “You came.”","<b>Scene 3 — Worst moment</b> (map: Middle 2): Sprints. Mateo trips in front of everyone and thinks about the gate.","<b>Scene 4 — What he does</b> (map: Middle 3): Penalty kicks, knee bleeding. Diego pulls him up. Mateo lines up first.","<b>Scene 5 — Ending</b> (map: End): Walking off with the list. “Next year I won’t be scared.”"],
   notice="One line each, and nothing new: every scene was already on the map. Sam doesn’t know every word yet. He knows where each scene starts and what it’s for. That’s enough to begin."),
 tool=dict(title="Five-scene list", intro="Each scene has a job. One line per scene.",
   filled=["<b>1 Opening</b> ← your map’s Beginning — a lead, the setting, what your kid wants","<b>2 First wall</b> ← Middle 1 — the first thing that gets in the way","<b>3 Worst moment</b> ← Middle 2 — a choice under pressure","<b>4 What they do</b> ← Middle 3 — your kid acts","<b>5 Ending</b> ← your map’s End — how it lands, what changed"],
   yourturn="1: ____ · 2: ____ · 3: ____ · 4: ____ · 5: ____"),
 frames=["Scene 1: [Kid] is ___ and wants ___.","Scene 2: Then ___.","Scene 3: The worst part is when ___.","Scene 4: So [kid] ___.","Scene 5: In the end, ___."],
 ms="Today: paste your five-scene list at the top of this box. It will sit above your story as you write it, so you always know what’s next.",
 prompt="Turn your map from yesterday into five scenes, one line each, in the box below (Beginning → Scene 1, the three middle things → Scenes 2, 3, 4, End → Scene 5). Then copy the list into My Story above so it’s there when you start drafting next week.",
 ph="1 Opening: ___ / 2 First wall: ___ / 3 Worst moment: ___ / 4 What they do: ___ / 5 Ending: ___")

# ---------------------------------------------------------------- WEEK 10 · DRAFT THE OPENING
card(10,1, sub="Day 1: Six ways in",
 focus="This week you start writing the story for real. Today is only the first sentence. Its one job is to make a reader want the second sentence. There are six kinds of first sentence that do that. You will try two and pick one.",
 anne="Chapter 16 opens with a page about October at Green Gables — and then the real chapter starts the minute Marilla says Diana can come to tea. Skip the October. Start where it starts.",
 watch=dict(intro="Sam is ready to write his opening. First he writes the sentence that came into his head.",
   before="It was a sunny day. Mateo woke up. He was nervous about soccer tryouts.",
   after="“You’re going to be late!” Mom shouted up the stairs. Mateo froze with one cleat on.",
   notice="The first version tells you the weather and then tells you the feeling. The second drops you into the house. You hear Mom. You see the cleat. You already know something is wrong, and nobody said “nervous.”"),
 tool=dict(title="Six leads", intro="Sam tried all six for his story. He picked #2.",
   filled=["<b>1. Question</b> — Have you ever wanted something so badly you almost didn’t try?","<b>2. Dialogue ✓</b> — “You’re going to be late!” Mom shouted up the stairs.","<b>3. Action</b> — Mateo tied his cleat. He untied it. He tied it again.","<b>4. Sound</b> — RIIIING. The alarm. Then Mom, yelling his name.","<b>5. Snapshot</b> — The cleats sat by the door, untouched.","<b>6. Flashback</b> — Mateo had wanted to make this team since he was seven."],
   yourturn="Pick TWO. Write one sentence for each. Star the one you’ll use tomorrow."),
 frames=["Have you ever ___?","“___,” [someone] [shouted / whispered].","[Kid] [did something small]. Then [did it again].","The ___ sat ___, untouched.","[Kid] had wanted ___ since ___."],
 ms="Nothing here yet — tomorrow Scene 1 goes in. Your five-scene list from Week 9 should be at the top.",
 prompt="Write TWO different first sentences for your story, using two different leads from the list. Label each with its lead type. Put a star by the one you’ll use tomorrow.",
 ph="Lead type ___: ___ / Lead type ___: ___ ★")

card(10,2, sub="Day 2: Scene 1",
 focus="Today Scene 1 goes into My Story. Four to six sentences: your lead from yesterday, then where your kid is, then what they want. Don’t explain the problem yet. Just make us want the same thing your kid wants.",
 anne="Chapter 18: Minnie May is sick, the grown-ups are gone, and Anne knows what to do. Montgomery puts us in the room in two sentences and then lets Anne want something.",
 watch=dict(intro="Sam’s Scene 1, written today:",
   page=[SAM_S1],
   notice="Five sentences. The lead. Where he is (the stairs, the cleat). What he wants (the team). And one sentence that hints at the wall (he also wants to skip it) without naming it. That’s all Scene 1 has to do."),
 tool=dict(title="Scene 1 recipe", intro="Lead → where and when → what your kid wants → one hint of the wall.",
   filled=["Sam’s: Mom shouting · his room, morning · make the team · wants to skip it"],
   yourturn="Lead: ____ · Where/when: ____ · Want: ____ · Hint of the wall: ____"),
 frames=["[Your lead].","[Kid] was in ___, and it was ___.","More than anything, [kid] wanted ___.","But part of [kid] wanted to ___."],
 ms="Today: add Scene 1 (4–6 sentences) under your scene list. This box saves on this computer, in this browser. If you switch computers, keep a copy somewhere else too.",
 prompt="After Scene 1 is in My Story, write here: which lead did you use, and what does your kid want? One or two sentences.",
 ph="I used a ___ lead. My kid wants ___.")

card(10,3, sub="Day 3: Scene 2",
 focus="Scene 2 is the first thing that gets in the way. Your kid tries, or almost tries, and something makes it harder. Put one line of thinking inside their head — the words they’d never say out loud.",
 anne="Chapter 19: the concert, the spare-room bed, and a very surprised Aunt Josephine. One race to the bed, and the whole night turns. What Anne thinks while it’s happening is what makes us feel it.",
 watch=dict(intro="Sam’s Scene 2:",
   page=[SAM_S2],
   notice="The wall isn’t a person being mean. It’s twenty kids who look like they belong, and one friend who noticed him. The inner line is three words, repeated. You know exactly what he’s feeling and Sam never said “scared.”"),
 tool=dict(title="Scene 2 recipe", intro="The kid tries → the wall shows up → one line of inner thought.",
   filled=["Sam’s: arrives at the field · everyone looks better than him · “Don’t throw up.”"],
   yourturn="Kid tries: ____ · Wall shows up: ____ · Inner line: “____”"),
 frames=["[Kid] [tried to] ___.","That was when ___.","Inside, [kid] thought: ___.","“___,” [other person] said. [Kid] just ___."],
 ms="Today: add Scene 2 under Scene 1. You should have two scenes when you close this page.",
 prompt="Copy the one line of inner thought you gave your kid in Scene 2. Then one sentence: what does that line tell a reader that “he was nervous” wouldn’t?",
 ph="My kid's inner line: \"___\" / It shows ___.")

card(10,4, sub="Day 4: Read it back",
 focus="Two scenes are on the page. Read them from the top, out loud if you can. Check the word count under My Story — most stories are around 80–120 words right now. Then think about the thing that makes your kid special, because next week it’s going to cause trouble.",
 anne="Chapter 20: Anne’s imagination, the thing we love her for, is exactly what gets her stuck in the Haunted Wood. A gift and a problem can be the same thing.",
 watch=dict(intro="Sam reads his two scenes back and counts: 94 words. Then he thinks about Mateo’s gift.",
   page=["<b>Gift:</b> Mateo cares more than anyone else on that field.","<b>Problem:</b> Caring that much makes quitting feel safer than failing."],
   notice="The gift and the problem are the same thing, seen from two sides. Next week, that’s what Scene 3 is made of."),
 tool=dict(title="Gift → problem", intro="Name your kid’s best quality. Then name how it could hurt them.",
   filled=["Gift: the thing people like about them, or the thing they’re good at","Problem: the moment that same thing makes the wall taller"],
   yourturn="My kid’s gift is ____. It becomes a problem when ____."),
 frames=["My kid’s gift is ___.","It becomes a problem when ___.","Right now my story has ___ words and ___ scenes.","The sentence I like best so far is ___."],
 ms="Read only today. Fix any sentence that made you stumble when you read it out loud.",
 prompt="What is your kid’s greatest gift, and how could that same gift become a problem? Two or three sentences. Then write your word count.",
 ph="My kid's gift is ___. It could become a problem when ___. Word count: ___")

# ---------------------------------------------------------------- WEEK 11 · RISING ACTION
card(11,1, sub="Day 1: Order and transitions",
 focus="The middle of a story is where pressure builds, and it only works if the reader can follow the order. Today you take the three middle scenes from your list — Scene 2 (written), Scene 3 and Scene 4 (this week) — and give each one a transition word to start on, so nobody gets lost.",
 anne="Chapter 21: the liniment cake only works as a story because we get every step in order — the vanilla bottle, the guests, the first bite. Order is the joke.",
 watch=dict(intro="Sam writes the first line of each middle scene plain, then gives each one a transition word.",
   before="Mateo got to the field. They did sprints and he tripped. Diego helped him. They did penalty kicks.",
   after="At the field, twenty boys were already kicking balls around. First came sprints — and Mateo tripped on his own foot. Then a hand came down in front of his face. After that, penalty kicks.",
   notice="Same events, in the same order, but now each scene opens with a word that tells you where you are in time: at, first, then, after that. Those are the first words of Sam’s Scenes 2, 3 and 4. He’s already written Scene 2; you’ll watch him write 3 and 4 this week."),
 tool=dict(title="Stoplight + transitions", intro="Your five scenes on the stoplight. The three middle ones each get a transition word to open on.",
   filled=["\U0001F7E2 Scene 1 — Opening (written): Mom shouts up the stairs.","\U0001F7E1 Scene 2 — First wall (written): <b>At the field,</b> twenty boys…","\U0001F7E1 Scene 3 — Worst moment: <b>First</b> came sprints…","\U0001F7E1 Scene 4 — What he does: <b>Then</b> a hand came down…","\U0001F534 Scene 5 — Ending: <b>In the end,</b> …","<b>Transition bank:</b> First, Next, Then, After that, Suddenly, Meanwhile, Just then, Finally, At last, In the end."],
   yourturn="Scene 2 starts with: ____ · Scene 3 will start with: ____ · Scene 4 will start with: ____ · Scene 5 will start with: ____"),
 frames=["First, [kid] ___.","Next, ___.","Suddenly, ___.","Just then, ___.","Finally, ___."],
 ms="Read only today. Look at Scene 2 — does it have a transition word anywhere? Add one if it needs it.",
 prompt="Fill in your own stoplight: for Scenes 2, 3 and 4, write the transition word the scene starts with, then what happens in it. One line each. Scene 2 is already in My Story — check it has one. Scenes 3 and 4 you write this week.",
 ph="Scene 2 (At / First…): ___ / Scene 3 (Then…): ___ / Scene 4 (After that…): ___")

card(11,2, sub="Day 2: Scene 3, the worst moment",
 focus="Scene 3 is the worst moment. Your kid faces a choice under pressure: what they want against what they fear. This is where last week’s gift turns into the problem. Write it so the reader can feel both. Stop the scene right before your kid decides.",
 anne="Chapter 23: the ridgepole. Josie dares her, everyone is watching, and Anne has to choose between falling and backing down. Montgomery makes us wait.",
 watch=dict(intro="Sam’s Scene 3, first draft (he’ll fix it in Week 12):",
   page=[SAM_S3_DRAFT],
   notice="The pressure is everyone watching. The want is the team. The fear is right there in the gate, twenty steps away — and Mateo’s gift, caring more than anyone, is exactly why the gate looks so good. Sam stops before Mateo decides. The reader has to turn the page."),
 tool=dict(title="Pressure scene", intro="Want on one side, fear on the other. End before the choice.",
   filled=["<b>What they want:</b> to finish, to belong, to make the team","<b>What they fear:</b> everyone laughing — and the gate is right there","<b>Stop here:</b> before he gets up or walks off"],
   yourturn="Want: ____ · Fear: ____ · The moment I stop: ____"),
 frames=["[Kid] knew they could ___ or ___.","Everyone was watching when ___.","[Kid] looked at ___. It was only ___ away.","Part of [kid] wanted to ___. The other part ___."],
 ms="Today: add Scene 3 under Scene 2. Start it with a transition word from yesterday.",
 prompt="Write Scene 3 in My Story (3–5 sentences): a choice under pressure. Then, here, one sentence: what does your kid want in that moment, and what do they fear?",
 ph="In Scene 3 my kid wants ___ but fears ___.")

card(11,3, sub="Day 3: Scene 4, what they do",
 focus="Scene 4 is your kid acting. Not being rescued, not getting lucky — doing something. It can be small. Getting up counts. Include one transition word and one line of dialogue.",
 anne="Chapter 24: Miss Stacy’s concert. Anne stops being the kid things happen to and starts being the kid who does things. Same for your kid.",
 watch=dict(intro="Sam’s Scene 4, first draft:",
   page=[SAM_S4_DRAFT],
   notice="Diego’s hand is help, but Mateo does the getting up. He walks back. He’s first in line. He kicks and misses and doesn’t care. Four actions, and the last one is the change from Week 8."),
 tool=dict(title="Action + transition + dialogue", intro="Three things your kid does, one word that connects, one thing somebody says.",
   filled=["<b>Actions:</b> got up · walked back · first in line","<b>Transition:</b> Then","<b>Dialogue:</b> “Are you okay?” (Sam will change this in Week 12)"],
   yourturn="Action 1: ____ · Action 2: ____ · Action 3: ____ · Transition: ____ · Line: “____”"),
 frames=["Then [kid] ___.","[Kid] didn’t ___. [Kid] ___.","“___,” [other person] said.","It went ___. [Kid] didn’t care."],
 ms="Today: add Scene 4 under Scene 3. Your kid has to DO something in it.",
 prompt="Write Scene 4 in My Story (3–5 sentences). Then, here: list the three things your kid DOES in that scene, in order.",
 ph="1. ___ 2. ___ 3. ___")

card(11,4, sub="Day 4: Get to the end",
 focus="Today you finish the first draft. Scene 5 is the ending, and today it only has to exist. A rough ending is better than no ending — you’ll make it strong in Week 14. Two or three sentences. Just land it.",
 anne="Chapter 25: the puffed sleeves finally arrive. A want from Chapter 11 gets its ending fourteen chapters later. Every want in your story needs an ending too.",
 watch=dict(intro="Sam’s rough Scene 5 — the ending he writes today, knowing he’ll fix it later:",
   page=[SAM_S5_ROUGH],
   notice="It’s bad. Sam knows it’s bad. But his story now has a beginning, a middle, and an end, which means next week he can revise a whole story instead of half of one."),
 tool=dict(title="The finish line", intro="Two or three sentences. Answer: what happened, and how does your kid feel?",
   filled=["Sam’s: made the team · happy · the end","Yours can be just as rough. It’s a placeholder."],
   yourturn="What happened: ____ · How my kid feels: ____"),
 frames=["In the end, [kid] ___.","[Kid] ___. It was over.","[Kid] felt ___ for the first time all day.","That was the end of ___."],
 ms="Today: add a rough Scene 5. Then read the whole thing top to bottom. Check the word count — you’re probably around 180–250 now.",
 prompt="After your rough ending is in My Story, look back at your whole draft. Has the conflict GROWN since Scene 1? Write 2–3 sentences: (1) what your kid wanted at the start, (2) what they feared most in Scene 3, (3) one thing that made it worse.",
 ph="At the start, my kid wanted ___. In Scene 3 they feared ___. It got worse when ___.")

# ---------------------------------------------------------------- WEEK 12 · REVISE
card(12,1, sub="Day 1: ARMS — Add",
 focus="Revising is big changes, not fixing typos. This week you use ARMS: Add, Remove, Move, Substitute. Today is A. Find one place where your story moves too fast — where you skipped something the reader needed — and add it.",
 anne="Chapter 26: the story club. Anne’s stories are all plot — people die, people are rescued — and she has to learn to add the real parts. So does everyone.",
 watch=dict(intro="Sam reads Scene 3 and finds the place that goes too fast: Mateo falls, and we never feel it. He adds.",
   before="Halfway down the field Mateo’s left cleat caught his right one and he went down in front of everyone. He lay there and thought about the gate.",
   after="Sweat ran down Mateo’s neck. He could hear his heart in his ears. Halfway down the field his left cleat caught his right one and he went down in front of everyone. Mateo lay there with grass in his mouth and thought about the gate.",
   notice="Three added details: sweat, the heartbeat, grass in his mouth. Now the fall takes as long to read as it took to happen."),
 tool=dict(title="ARMS: Add", intro="Where does your story jump over something the reader needed?",
   filled=["<b>A</b>dd — a sensory detail, a body detail, one line of dialogue, or a missing step","<b>R</b>emove — tomorrow","<b>M</b>ove — tomorrow","<b>S</b>ubstitute — Day 3"],
   yourturn="The place that moves too fast: ____. What I will ADD there: ____."),
 frames=["I will ADD a ___ detail where ___.","The reader needs to know ___ before ___.","Right after ___, I’ll add ___.","The place that goes too fast is ___."],
 ms="Today: find your too-fast spot and add to it, right in the draft. Word count should go up by 10–30.",
 prompt="Pacing pass. Find ONE place that moves too fast and write the 1–3 sentences you added there. Then find ONE place that drags, and say what you’d cut (you’ll cut it tomorrow).",
 ph="Added here (___): ___ / Will cut here (___): ___")

card(12,2, sub="Day 2: ARMS — Remove and Move",
 focus="Two moves today. REMOVE: cut a sentence that doesn’t belong in its scene, even if you like it. MOVE: find a sentence that’s in the wrong place and put it where it hits hardest.",
 anne="Chapter 28: the lily maid. Montgomery cuts straight to the boat sinking. No pages of setup. Everything that doesn’t serve the scene is gone.",
 watch=dict(intro="Sam cuts one sentence and moves another in Scene 3.",
   before="Coach yelled “FASTER!” like he meant it. Mateo’s dad came to watch. Sweat ran down Mateo’s neck. … He lay there and thought about the gate. It was only twenty steps away. Somebody laughed.",
   after="Coach yelled “FASTER!” like he meant it. Sweat ran down Mateo’s neck. … he went down in front of everyone. Somebody laughed. Mateo lay there with grass in his mouth and thought about the gate. It was only twenty steps away.",
   notice="REMOVED the dad sentence — it interrupts the sprint and never comes back. MOVED “Somebody laughed” up to right after the fall, where it stings. Now the gate is the last thing in the scene."),
 tool=dict(title="ARMS: Remove + Move", intro="Cut one. Move one.",
   filled=["<b>R</b>emove — a sentence that interrupts the scene, repeats something, or belongs somewhere else","<b>M</b>ove — a line that would hit harder earlier or later (the last sentence of a scene is the strongest spot)"],
   yourturn="I will REMOVE: ____ (because ____). I will MOVE ____ to ____."),
 frames=["I will REMOVE the part where ___ because ___.","I will MOVE ___ to right after ___.","The last sentence of Scene ___ should be ___.","___ interrupts the scene, so it goes."],
 ms="Today: make the cut and the move, right in the draft. It’s okay if the word count goes down.",
 prompt="Write the one sentence you cut and why. Then write the sentence you moved, and where it lives now.",
 ph="Cut: \"___\" because ___ / Moved: \"___\" to ___")

card(12,3, sub="Day 3: ARMS — Substitute",
 focus="SUBSTITUTE means swap something weak for something true. Three swaps today: one boring verb for a strong one, one line of dialogue for what that person would really say, and one small action that only your kid would do.",
 anne="Chapter 29: Anne in Charlottetown. It’s the small things she notices — not the big ones — that tell you who she is. Small and true beats big and vague.",
 watch=dict(intro="Sam makes three swaps in Scene 4.",
   before="“Are you okay?” Diego said. Mateo got up. … He kicked the ball.",
   after="He didn’t say anything. He just pulled. Mateo got up. … He slammed the ball.",
   notice="“Are you okay?” is what anyone would say. Diego pulling without a word is what Diego would do. And kicked → slammed: one verb, and now you can hear it."),
 tool=dict(title="ARMS: Substitute", intro="Three swaps.",
   table=[["Swap","Sam’s"],["A boring verb → a strong one","kicked → slammed"],["A line anyone would say → a line THIS person would say (or do)","“Are you okay?” → he just pulled"],["A general action → one only your kid would do","(Mateo’s cleat habit is already in Scene 1)"]],
   yourturn="Verb: ____ → ____ · Line: “____” → “____” · Action only my kid would do: ____"),
 frames=["I changed ___ to ___.","[Other person] wouldn’t say ___. They’d ___.","The small thing only [kid] would do is ___.","Instead of ___, [kid] ___."],
 ms="Today: make your three swaps in the draft. Read the dialogue out loud first — it’s the fastest way to hear a fake line.",
 prompt="Write your three swaps: the verb (before → after), the line of dialogue (before → after), and the small action you added that only your kid would do.",
 ph="Verb: ___ → ___ / Line: \"___\" → \"___\" / Small action: ___")

card(12,4, sub="Day 4: Read the whole thing",
 focus="Your draft has been through Add, Remove, Move and Substitute. Today, read it start to finish without stopping to fix anything. Then answer two questions: what’s the strongest part, and what still needs work.",
 anne="Chapter 30: the Queen’s class. Anne stops and takes stock of where she is and where she’s going. Do that with your story.",
 watch=dict(intro="Sam reads his five scenes top to bottom.",
   page=["<b>Strongest:</b> Scene 3. The fall, the grass, the gate twenty steps away.","<b>Still needs work:</b> Scene 5. “Mateo made the team. He was happy. The end.” It’s still the placeholder."],
   notice="Sam doesn’t fix Scene 5 today. He names it. Week 14 is for endings. Knowing what’s weak is the work today."),
 tool=dict(title="Two-question reread", intro="Read it all. Then only two answers.",
   filled=["<b>Strongest part</b> — name the scene and the sentence","<b>Still needs work</b> — name the scene and what’s wrong with it"],
   yourturn="Strongest: Scene ____, “____” · Needs work: Scene ____, because ____"),
 frames=["The strongest part is Scene ___, where ___.","The sentence I’d keep no matter what is ___.","Scene ___ still needs work because ___.","Next week I want to fix ___."],
 ms="Read only today. Don’t fix. Just notice.",
 prompt="Read your whole draft. Write 2–3 sentences: what is the strongest part (name the scene and a sentence), and what still needs work (name the scene and why)?",
 ph="Strongest part: Scene ___, \"___\". Still needs work: Scene ___ because ___.")

# ---------------------------------------------------------------- WEEK 13 · EDIT
card(13,1, sub="Day 1: CUPS — Capitals and end punctuation",
 focus="Editing is the small stuff, and it’s slow work: you read line by line. This week you use CUPS — Capitals, Usage, Punctuation, Spelling. Today is C and the end of P: every sentence starts with a capital and ends with a mark.",
 anne="Chapter 31, “Where the Brook and River Meet.” Anne is careful now in a way she never used to be. Editing is being careful on purpose.",
 watch=dict(intro="The Watch How panels showed you Sam’s scenes cleaned up. The box he typed them in, fast, has slips in it — every draft does. Today he reads Scene 1 line by line and finds two.",
   before="Mateo froze with one cleat on. today was tryouts he had wanted to make the team since he was seven.",
   after="Mateo froze with one cleat on. Today was tryouts. He had wanted to make the team since he was seven.",
   notice="A missing capital on Today, and two sentences that ran together with no period. Small. But a reader trips on them, and a tripping reader stops feeling the story."),
 tool=dict(title="CUPS: C + P (ends)", intro="Read line by line. Check two things per line.",
   filled=["<b>C</b>apitals — start of every sentence; names; places; days; “I”","<b>P</b>unctuation (ends) — every sentence ends with . ? or !","<b>U</b>sage — Day 3","<b>S</b>pelling — Day 3"],
   yourturn="Fix 1: ____ · Fix 2: ____ · Fix 3: ____"),
 frames=["I found a missing capital in ___.","I added a period after ___.","___ and ___ were one sentence; now they’re two.","I capitalized ___ because it’s a name."],
 ms="Today: read every line of your draft and fix capitals and end marks right in the box.",
 prompt="EDIT pass. Read your whole draft slowly, line by line. Fix every missing capital and every missing end mark in My Story. Then list three fixes you made here.",
 ph="Three fixes: 1) ___ 2) ___ 3) ___")

card(13,2, sub="Day 2: CUPS — Dialogue punctuation",
 focus="Dialogue has its own rules, and readers notice when they’re broken. Quotation marks around the words. A comma before the tag. A capital letter starting the speech. Read every line of dialogue out loud today.",
 anne="Chapter 32: the pass list. Read the dialogue in that chapter aloud and every line sounds like the person saying it — and every line is punctuated so you can tell who’s talking.",
 watch=dict(intro="Sam checks every line of dialogue in his story. He finds one in Scene 2.",
   before="Diego jogged over. You came he said.",
   after="Diego jogged over. “You came,” he said.",
   notice="Quotation marks so the reader knows it’s spoken. A comma before he said. The words are the same; now you can hear them."),
 tool=dict(title="Dialogue check", intro="Three things every line of dialogue needs.",
   filled=["<b>Quotation marks</b> around the spoken words","<b>A comma</b> before the tag (“You came,” he said) — or a ? or ! if the speech needs one","<b>A capital letter</b> on the first word of the speech","<b>Bonus:</b> new speaker, new line"],
   yourturn="Line I fixed: “____” → “____”"),
 frames=["“___,” [person] said.","“___?” [person] asked.","[Person] [action]. “___.”","I fixed the line where ___ says ___."],
 ms="Today: fix every line of dialogue in the draft. If a line sounds fake out loud, rewrite it too.",
 prompt="Read every line of dialogue in your draft out loud. Find ONE line that doesn’t sound right or isn’t punctuated right. Write it before and after. Then check: quotation marks, comma before the tag, capital on the speech.",
 ph="Before: \"___\" / After: \"___\"")

card(13,3, sub="Day 3: CUPS — Usage, spelling, run-ons",
 focus="Usage means the right word: their / there / they’re, two / too / to, your / you’re. Spelling means every word looked up if you’re not sure. And run-ons: a sentence that should be two, split it.",
 anne="Chapter 33: the hotel concert. Anne’s recitation works because every single word is right. One wrong word and the spell breaks.",
 watch=dict(intro="Sam finds three things in Scene 4.",
   before="His knee was bleeding a litle he walked back to the line. When Coach called penalty kicks, he was the first one their.",
   after="His knee was bleeding a little. He walked back to the line. When Coach called penalty kicks, he was the first one there.",
   notice="Spelling (litle → little). A run-on split into two. Usage (their → there). Three fixes in two lines, and Sam only found them because he read slowly."),
 tool=dict(title="CUPS: U + S + run-ons", intro="Three checks per line.",
   table=[["Check","Ask"],["Usage","their / there / they’re? two / too / to? your / you’re?"],["Spelling","Would I bet on this word? If not, look it up."],["Run-on","Could this be two sentences? Then it should be."]],
   yourturn="Run-on fixed: ____ · Usage fixed: ____ · Spelling fixed: ____"),
 frames=["I fixed [their / there / they’re] in ___.","I split “___” into two sentences.","I looked up ___ and it’s spelled ___.","I changed ___ to ___."],
 ms="Today: fix usage, spelling and run-ons in the draft. Read slowly. Slower than feels normal.",
 prompt="Grammar and spelling pass. Find ONE run-on in your draft and split it. Find ONE usage or spelling fix. Write the corrected versions here.",
 ph="Run-on fixed: ___ / Other fix: ___")

card(13,4, sub="Day 4: Read it aloud",
 focus="The last edit is your ears. Read your whole story out loud, slowly, to yourself. Anywhere you stumble, something is wrong with the sentence. Fix it. Then say what you’re proud of and what you’d change with more time.",
 anne="Chapter 34: a Queen’s girl. Anne reads her own life back to herself — the good parts and the parts she’d change. Do that with your story.",
 watch=dict(intro="Sam reads his story out loud and catches one more, in Scene 3: a sentence he ran out of breath on.",
   before="Halfway down the field his left cleat caught his right one and he went down in front of everyone and somebody laughed and he lay there with grass in his mouth.",
   after="Halfway down the field his left cleat caught his right one and he went down in front of everyone. Somebody laughed. Mateo lay there with grass in his mouth.",
   notice="He didn’t see it. He heard it — one breath wasn’t enough. That’s what reading aloud is for."),
 tool=dict(title="Read-aloud checklist", intro="Read the whole thing out loud. Slowly.",
   filled=["☐ Anywhere I stumbled — fixed","☐ Anywhere I ran out of breath — split the sentence","☐ Anywhere I said a word that isn’t on the page — decide which is right","☐ The dialogue sounds like people"],
   yourturn="Most proud of: ____ · Would change with more time: ____"),
 frames=["I’m most proud of ___ because ___.","If I had more time, I would ___.","The sentence I stumbled on was ___.","Reading it aloud, I noticed ___."],
 ms="Today: read the whole story aloud. Fix what you hear. Next week you publish it.",
 prompt="FINAL POLISH. Read your story aloud one more time and fix what you hear. Then write 2–3 sentences: what you are most proud of in this story, and what you would change if you had more time.",
 ph="Most proud of: ___. Would change: ___.")

# ---------------------------------------------------------------- WEEK 14 · PUBLISH
card(14,1, sub="Day 1: A strong ending",
 focus="Publishing starts with the ending, because your rough Scene 5 from Week 11 is still sitting there. A strong ending does one of four things: circles back to your opening, tells the feeling, names the lesson, or shares a hope for the future. Pick one and rewrite Scene 5.",
 anne="Chapter 35: winter at Queen’s. The end of the book is coming into view, and Montgomery starts pointing back at the beginning. Endings that remember the beginning feel finished.",
 watch=dict(intro="Sam replaces the rough ending he wrote in Week 11.",
   before=SAM_S5_ROUGH,
   after=SAM_S5_STRONG,
   notice="The new one circles back (the field that looked huge now feels small), shares a hope (next year), and lets Diego be Diego. And it doesn’t say “happy” anywhere."),
 tool=dict(title="Strong endings", intro="Pick ONE move.",
   table=[["Move","Sam’s version"],["Circle back to your opening","Start: the field looked huge. End: the field felt small."],["Tell the feeling","“Mateo felt steady for the first time all day.”"],["Name the lesson","“Being scared and trying anyway is what brave is.”"],["Share a hope","“Next year I won’t be scared at all.”"]],
   yourturn="☐ Circle back · ☐ Tell the feeling · ☐ Name the lesson · ☐ Share a hope"),
 frames=["In the end, [kid] knew ___.","The same ___ that ___ now ___.","“Next ___,” [kid] said, “___.”","That was the day [kid] learned ___."],
 ms="Today: delete your rough Scene 5 and write the real one, 3–5 sentences.",
 prompt="Pick ONE strong-ending move. Rewrite Scene 5 in My Story. Then, here: which move did you pick, and copy your new last sentence.",
 ph="My move: ___. My last sentence: \"___\"")

card(14,2, sub="Day 2: Score it yourself",
 focus="Today you score your own story against a rubric — the same kind a teacher uses — so you know what’s strong and what still needs work. Then you pick ONE row to make better before you publish. Not everything. One.",
 anne="Chapter 36: the Avery scholarship. Anne is judged, and she takes the judging well. Scoring your own work honestly is a skill, and it’s harder than it sounds.",
 watch=dict(intro="Sam scores his story 1–3 in five rows, then picks one to fix.",
   page=["<b>Ideas</b> 3 ✓ · <b>Organization</b> 3 ✓ · <b>Word Choice</b> 2 (a few plain words in Scene 2) · <b>Voice</b> 3 ✓ · <b>Conventions</b> 2 (one comma he’s not sure about)","Sam picks <b>Word Choice</b>. He goes back to Scene 2 and changes “kicking balls around” to “juggling balls off their knees.” One fix."],
   notice="Sam didn’t try to fix everything. He picked one row that scored a 2 and made it a 3. That’s a real publish-week move: one targeted fix."),
 tool=dict(title="Realistic Fiction Rubric (self-score)", intro="Score yourself 1, 2 or 3 in each row. Be honest.",
   table=[["Row","3 (strong)","2 (ok)","1 (weak)"],["Ideas","a real kid, a real problem, interesting","somewhat","vague"],["Organization","five scenes, clear order, strong start and end","middle could be stronger","confusing order"],["Word Choice","specific, vivid","some plain words still","very plain"],["Voice","sounds like a real person","some feeling","flat"],["Conventions","capitals, punctuation, spelling right","a few slips","many slips"]],
   yourturn="Ideas __ · Organization __ · Word Choice __ · Voice __ · Conventions __ → the ONE row I’ll fix: ____"),
 frames=["My strongest row is ___ because ___.","The row I want to improve is ___.","I will fix ___ by changing ___.","After the fix, ___ is a 3."],
 ms="Today: make your one targeted fix in the draft.",
 prompt="Score your story 1–3 in all five rows. Then pick ONE row to improve and name TWO specific things you changed in your draft to do it.",
 ph="Ideas: __ Organization: __ Word Choice: __ Voice: __ Conventions: __ / I improved ___ by: 1) ___ 2) ___")

card(14,3, sub="Day 3: Title page",
 focus="Today your story gets the parts that make it feel like a real book: a title, an author line, and a dedication. The title should hint at the conflict, not just name the topic.",
 anne="Chapter 37. Read it, and then write your dedication. You’ll know who it’s for.",
 watch=dict(intro="Sam designs his title page.",
   before="Soccer Story by Sam",
   after="The Day I Almost Didn’t Try · A story by Sam · For Mom, who said “try anyway.”",
   notice="The title hints at the conflict (Almost Didn’t Try). The author line sounds like an author. The dedication is one sentence to a real person who matters."),
 tool=dict(title="Title page + dedication", intro="Three parts.",
   filled=["<b>TITLE</b> — hints at the conflict, not the topic. “The Day ___” and “How ___” both work.","<b>AUTHOR</b> — A story by ___","<b>DEDICATION</b> — For ___, who ___ (one sentence, one real person)"],
   yourturn="Title: ____ · A story by ____ · For ____, who ____"),
 frames=["The Day [Kid] ___ (title)","How [Kid] ___ (title)","For [person], who ___. (dedication)","To [person], the one who ___. (dedication)"],
 ms="Today: put your title, author line and dedication at the very top of My Story, above Scene 1. Delete the five-scene list — you don’t need it anymore.",
 prompt="Design your title page. Write a TITLE that hints at the conflict. Add your name as the author. Write a one-sentence DEDICATION to someone who matters to you. Put all three at the top of My Story too.",
 ph="Title: ___. A story by ___. For ___, who ___.")

card(14,4, sub="Day 4: Share and reflect",
 focus="Your story is finished. Today you read it aloud to someone — slowly, with feeling, pausing where it matters. Then you write a short reflection on two things that grew over these eight weeks: Anne, and your writing.",
 anne="Chapter 38: the bend in the road. Anne’s story ends with a choice she makes on purpose. So does yours: you chose every word.",
 watch=dict(intro="Sam reads his story aloud at dinner. Then he writes a reflection. First try, then a better one.",
   before="I wrote a story. It was good. I learned a lot.",
   after="When we started this story I thought a story was just events in a row. Now I know a story is what a kid WANTS, what GETS IN THE WAY, and what they DO about it. Mateo wanted the team. Fear got in the way. He got up anyway. That’s the shape.",
   notice="The second one is specific. What he used to think, what he knows now, and one clear example from his own story. Specific always beats general — that was true in Week 7 and it’s true now."),
 tool=dict(title="Share + reflect", intro="Two parts.",
   filled=["<b>SHARE:</b> read your story aloud to someone. Slow down. Pause where it matters. Use your kid’s voice for the dialogue.","<b>REFLECT:</b> 3–4 sentences — one way Anne changed across the novel (with a detail), and one way your own writing got stronger in this story (with a detail)."],
   yourturn="I will read my story to ____. · Anne changed by ____. · My writing got stronger at ____."),
 frames=["When we started this story, I thought ___.","Now I know ___.","One example from my story is ___.","Anne changed from ___ to ___, and you can see it when ___."],
 ms="Your story is done. Read it one more time. Then read it to someone.",
 prompt="Final reflection. Write 3–4 sentences: (1) name ONE way Anne has changed across the novel, with a specific detail, and (2) name ONE thing about your own writing that got stronger while you wrote this story, with a specific example from it.",
 ph="Anne has changed by... A specific detail is... My own writing got stronger at... For example...")

assert len(CARDS) == 32, len(CARDS)
