"""Build assets/css/readable.css: a readability floor for every lesson page.

Scans the <style> blocks of every lesson/check-in/fluency page for rules that
set a font-size under 16px, and raises each one:
    uppercase label (text-transform:uppercase)   -> 14px
    anything else under 14px                     -> 16px
    14px                                         -> 16px
    15px                                         -> 17px
Inline style="font-size:Npx" under 16px is raised the same way (it cannot be
known whether it is a label, so under 13px -> 14px, 13px -> 15px).
Low-contrast text colours are darkened to pass 4.5:1 on white/cream.
Re-run after adding lessons:  python tools/build-readable.py
"""
import re, glob, io, collections
DARK = {'#7A88A8':'#56627F','#C7922C':'#8A6212','#34B76F':'#1E7A48','#C7627E':'#A03F5B',
        '#8B6FC0':'#6A4FA3','#55C8E8':'#1A6B8E','#999':'#666','#999999':'#666',
        '#A08A62':'#6E5C3A','#968260':'#6E5C3A','#A08F6C':'#6E5C3A','#9A8B6C':'#6E5C3A',
        '#8A7B5C':'#6E5C3A','#F9A825':'#8A6212','#D4A843':'#8A6212'}
def norm(c):
    c=c.upper()
    return c
def bump(px, upper):
    if px>=16: return None
    if upper: return 14 if px<14 else (16 if px<15 else 17)
    if px<14: return 16
    if px<15: return 16
    return 17
rules=collections.OrderedDict(); colors=collections.OrderedDict()
allcol=collections.defaultdict(set)   # every colour any page gives a selector
BARE=re.compile(r'(^|[\s>+~])[a-z][a-z0-9]*$')   # last part is a bare element
inline=set(); inline_col=set()
for f in sorted(glob.glob('*.html')):
    s=io.open(f,encoding='utf-8',errors='ignore').read()
    for st in re.findall(r'<style[^>]*>(.*?)</style>',s,re.S):
        st=re.sub(r'/\*.*?\*/','',st,flags=re.S)
        for m in re.finditer(r'([^{}]+)\{([^{}]*)\}',st):
            sel=' '.join(m.group(1).split()); body=m.group(2)
            if BARE.search(sel.split(',')[-1].strip()) and '.' not in sel.split(',')[-1] and '#' not in sel.split(',')[-1]: continue
            if sel.startswith('@') or "'" in sel or '"' in sel or sel in ('body','html','from','to') or re.match(r'^[\d.%, ]+$',sel): continue
            fm=re.search(r'(?<![-\w])font-size\s*:\s*([\d.]+)px',body)
            up=bool(re.search(r'text-transform\s*:\s*uppercase',body))
            if fm:
                n=bump(float(fm.group(1)),up)
                if n: rules[sel]=max(n,rules.get(sel,0))
            cm=re.search(r'(?<![-\w])color\s*:\s*(#[0-9A-Fa-f]{3,6})\b',body)
            if cm: allcol[sel].add(norm(cm.group(1)))
            if cm and norm(cm.group(1)) in DARK: colors[sel]=DARK[norm(cm.group(1))]
    t=re.sub(r'<style.*?</style>|<script.*?</script>','',s,flags=re.S)
    for m in re.finditer(r'style="([^"]*)"',t):
        for fm in re.finditer(r'font-size\s*:\s*([\d.]+)px',m.group(1)):
            if float(fm.group(1))<16: inline.add(fm.group(1))
        for cm in re.finditer(r'(?:^|;)\s*color\s*:\s*(#[0-9A-Fa-f]{3,6})',m.group(1)):
            if norm(cm.group(1)) in DARK: inline_col.add(cm.group(1))
HEAD = ("/* readable.css — a readability floor for every lesson page.\n"
        "   Generated by tools/build-readable.py. Do not edit by hand; edit the\n"
        "   script and re-run it. Nothing here makes text smaller.\n"
        "   Class rules are prefixed with html body, so they beat the lesson's own\n"
        "   rule of the same name but lose to anything more specific; only the\n"
        "   inline sizes and colours need !important.\n"
        "   Floors: labels in capitals 14px, everything else 16px, body text 17px. */\n")
out=[HEAD]
by=collections.defaultdict(list)
for sel,n in rules.items(): by[n].append(sel)
def pre(sels):
    return sorted(set('html body '+x.strip() for sel in sels for x in sel.split(',') if x.strip()))
for n in sorted(by):
    out.append(',\n'.join(pre(by[n]))+'\n{font-size:%dpx;}\n'%n)
def inl(px):
    p=float(px); return 14 if p<13 else (16 if p<15 else 17)
byi=collections.defaultdict(list)
for px in sorted(inline,key=float):
    for sp in ('font-size:%spx','font-size: %spx'):
        byi[inl(px)].append('[style*="%s"]'%(sp%px))
out.append('/* inline sizes written into the lesson HTML */\n')
for n in sorted(byi): out.append(',\n'.join(byi[n])+'\n{font-size:%dpx !important;}\n'%n)
out.append('/* colours too pale to read */\n')
byc=collections.defaultdict(list)
# only where no page gives the same selector some other colour (a white
# label on a dark band elsewhere must not be darkened)
for sel,c in colors.items():
    if all(x in DARK for x in allcol[sel]): byc[c].append(sel)
for c in sorted(byc): out.append(',\n'.join(pre(byc[c]))+'\n{color:%s;}\n'%c)
byic=collections.defaultdict(set)
for c in inline_col:
    d=DARK[norm(c)]
    for pat in ('[style^="color:%s"]','[style^="color: %s"]','[style*=";color:%s"]','[style*="; color:%s"]','[style*="; color: %s"]','[style*=";color: %s"]'):
        byic[d].add(pat%c)
for d in sorted(byic): out.append(',\n'.join(sorted(byic[d]))+'\n{color:%s !important;}\n'%d)
io.open('assets/css/readable.css','w',encoding='utf-8',newline='\n').write(''.join(out))
print(len(rules),'class rules,',len(inline),'inline sizes,',len(colors),'class colours,',len(inline_col),'inline colours')
