# Writes tools/video-shotlist.js: every G4 ELA video slot
# with its repo path, whether the .mp4 already exists, and the clip script. Feeds the Video Studio page.
import json,os,re,glob,gzip,base64,html
R=os.path.expanduser('~/mnt/optima-4th-ela')
os.chdir(R)
man=json.load(open('video-manifest.json'))
titles={}
for f in glob.glob('lesson-*.html'):
    m=re.match(r'lesson-(\d+)-(\d+|fluency)',f)
    if not m: continue
    key=f"{m[1]}-{m[2]}"
    t=re.search(r'<title>([^<]*)',open(f,encoding='utf-8',errors='ignore').read())
    t=html.unescape(t[1]) if t else f
    t=t.replace('Optima Academy Online — ','').replace(' (Sparkle)','')
    src=open(f,encoding='utf-8',errors='ignore').read()
    n=re.search(r'class="vp-notes">(.*?)</div>',src,re.S)
    notes=''
    if n:
        notes=html.unescape(re.sub(r'<[^>]+>','',n[1])).strip()
        notes=re.sub(r'^Teacher recording notes:\s*','',notes)
        notes=re.sub(r'\s+',' ',notes)
    titles[key]={'title':t,'file':f,'notes':notes}
def exists(p): return os.path.exists('assets/video/'+p+'.mp4')
lessons=[]
for k,v in man.items():
    m=re.match(r'g4ela-(\d+)-(\w+)',k); w=int(m[1]); d=m[2]
    key=f"{w}-{d}"
    L={'w':w,'d':d,'title':titles.get(key,{}).get('title',f'Lesson {w}.{d}'),'file':titles.get(key,{}).get('file',''),
       'clips':[{'id':'lesson','label':'Lesson video','path':k,'done':exists(k) or v['status']=='ready','script':titles.get(key,{}).get('notes',''),'notes':True}]}
    dj=f'data/lesson-{w}-{d}.json'
    if os.path.exists(dj):
        D=json.load(open(dj)); tr=D.get('transcripts',{})
        for sid,s in D.get('media',{}).items():
            if s.get('kind') not in ('audio','video') or not s.get('path'): continue
            L['clips'].append({'id':sid,'label':s.get('label',sid),'path':s['path'],'done':exists(s['path']),'script':tr.get(sid,'')})
    lessons.append(L)
lessons.sort(key=lambda L:(L['w'],99 if L['d']=='fluency' else int(L['d'])))
poems=[('Hope Is the Thing with Feathers','hope-is-the-thing-with-feathers','Mrs. Frisby'),('Who Has Seen the Wind?','who-has-seen-the-wind','Anne of Green Gables'),('There Will Come Soft Rains','there-will-come-soft-rains','Number the Stars'),('Sympathy','sympathy','Freedom Train'),('The Forest Remembers','forest-remembers','Prince Caspian')]
def poemScript(slug):
    f=os.path.join(R,'Planning docs','teacher-video-scripts',f'g4-teacher-scripts-poem-{slug}.md')
    if not os.path.exists(f): return ''
    t=open(f,encoding='utf-8').read()
    m=re.search(r'^## [^\n]*\n(.*)',t,re.S|re.M)
    return (m.group(1) if m else t).strip()
# a poem with a whole-poem film for its first poetry day (Number the Stars)
fullpoems=[('There Will Come Soft Rains','there-will-come-soft-rains','Number the Stars')]
extra={'poems':[{'id':'poem','label':f'{t} ({b})','path':'poem/'+s,'done':exists('poem/'+s),'script':''} for t,s,b in poems]+
 [{'id':'poem-full','label':f'{t}: whole poem, first poetry day ({b})','path':'poem/'+s+'-full','done':exists('poem/'+s+'-full'),'script':poemScript(s)} for t,s,b in fullpoems],
 'teacher':[{'id':'scrapbook','label':'Anne Character Growth Scrapbook — teacher video','path':'teacher/g4ela-anne-scrapbook','done':exists('teacher/g4ela-anne-scrapbook'),'script':''}]}
teacher={}
for f in sorted(glob.glob(os.path.join(R,'Planning docs','teacher-video-scripts','g4-teacher-scripts-*.md'))):
    k=re.search(r'g4-teacher-scripts-(\d+-(?:\d|fluency))\.md$',f)
    if k: teacher[k.group(1)]=open(f,encoding='utf-8').read()
extra['teacherDocs']=teacher
out=json.dumps({'lessons':lessons,**extra},ensure_ascii=False,separators=(',',':'))
open(os.path.join(R,'tools','video-shotlist.js'),'w',encoding='utf-8').write('/* generated by tools/video_shotlist.py: rerun it after adding lessons or clips */\nwindow.SHOTLIST='+out+';\n')
print(len(out), sum(len(L['clips']) for L in lessons), sum(c['done'] for L in lessons for c in L['clips']))
